// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// jc_cpp
SEXP jc_cpp(ComplexVector z, ComplexVector nu);
RcppExport SEXP _acousticTS_jc_cpp(SEXP zSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< ComplexVector >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(jc_cpp(z, nu));
    return rcpp_result_gen;
END_RCPP
}
// yc_cpp
SEXP yc_cpp(ComplexVector z, ComplexVector nu);
RcppExport SEXP _acousticTS_yc_cpp(SEXP zSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< ComplexVector >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(yc_cpp(z, nu));
    return rcpp_result_gen;
END_RCPP
}
// hc_cpp
SEXP hc_cpp(ComplexVector z, ComplexVector nu);
RcppExport SEXP _acousticTS_hc_cpp(SEXP zSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< ComplexVector >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(hc_cpp(z, nu));
    return rcpp_result_gen;
END_RCPP
}
// jc_deriv_cpp
SEXP jc_deriv_cpp(ComplexVector z, ComplexVector nu, int k);
RcppExport SEXP _acousticTS_jc_deriv_cpp(SEXP zSEXP, SEXP nuSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< ComplexVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(jc_deriv_cpp(z, nu, k));
    return rcpp_result_gen;
END_RCPP
}
// yc_deriv_cpp
SEXP yc_deriv_cpp(ComplexVector z, ComplexVector nu, int k);
RcppExport SEXP _acousticTS_yc_deriv_cpp(SEXP zSEXP, SEXP nuSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< ComplexVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(yc_deriv_cpp(z, nu, k));
    return rcpp_result_gen;
END_RCPP
}
// hc_deriv_cpp
SEXP hc_deriv_cpp(ComplexVector z, ComplexVector nu, int k);
RcppExport SEXP _acousticTS_hc_deriv_cpp(SEXP zSEXP, SEXP nuSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< ComplexVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(hc_deriv_cpp(z, nu, k));
    return rcpp_result_gen;
END_RCPP
}
// js_cpp
SEXP js_cpp(IntegerVector l, NumericVector z);
RcppExport SEXP _acousticTS_js_cpp(SEXP lSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type l(lSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(js_cpp(l, z));
    return rcpp_result_gen;
END_RCPP
}
// ys_cpp
SEXP ys_cpp(IntegerVector l, NumericVector z);
RcppExport SEXP _acousticTS_ys_cpp(SEXP lSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type l(lSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(ys_cpp(l, z));
    return rcpp_result_gen;
END_RCPP
}
// hs_cpp
SEXP hs_cpp(IntegerVector l, NumericVector z);
RcppExport SEXP _acousticTS_hs_cpp(SEXP lSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type l(lSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(hs_cpp(l, z));
    return rcpp_result_gen;
END_RCPP
}
// js_deriv_cpp
SEXP js_deriv_cpp(IntegerVector l, NumericVector z, int k);
RcppExport SEXP _acousticTS_js_deriv_cpp(SEXP lSEXP, SEXP zSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type l(lSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(js_deriv_cpp(l, z, k));
    return rcpp_result_gen;
END_RCPP
}
// ys_deriv_cpp
SEXP ys_deriv_cpp(IntegerVector l, NumericVector z, int k);
RcppExport SEXP _acousticTS_ys_deriv_cpp(SEXP lSEXP, SEXP zSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type l(lSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(ys_deriv_cpp(l, z, k));
    return rcpp_result_gen;
END_RCPP
}
// hs_deriv_cpp
SEXP hs_deriv_cpp(IntegerVector l, NumericVector z, int k);
RcppExport SEXP _acousticTS_hs_deriv_cpp(SEXP lSEXP, SEXP zSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type l(lSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(hs_deriv_cpp(l, z, k));
    return rcpp_result_gen;
END_RCPP
}
// dwba_fbs_cpp
ComplexVector dwba_fbs_cpp(NumericMatrix rpos, NumericVector k_sw, double theta, double h, double R, int subdivisions, double rel_tol, double abs_tol);
RcppExport SEXP _acousticTS_dwba_fbs_cpp(SEXP rposSEXP, SEXP k_swSEXP, SEXP thetaSEXP, SEXP hSEXP, SEXP RSEXP, SEXP subdivisionsSEXP, SEXP rel_tolSEXP, SEXP abs_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type rpos(rposSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k_sw(k_swSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type subdivisions(subdivisionsSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< double >::type abs_tol(abs_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(dwba_fbs_cpp(rpos, k_sw, theta, h, R, subdivisions, rel_tol, abs_tol));
    return rcpp_result_gen;
END_RCPP
}
// dwba_segment_integrals_cpp
ComplexMatrix dwba_segment_integrals_cpp(NumericMatrix rpos, NumericVector k_sw, double theta, double h, double R, int subdivisions, double rel_tol, double abs_tol);
RcppExport SEXP _acousticTS_dwba_segment_integrals_cpp(SEXP rposSEXP, SEXP k_swSEXP, SEXP thetaSEXP, SEXP hSEXP, SEXP RSEXP, SEXP subdivisionsSEXP, SEXP rel_tolSEXP, SEXP abs_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type rpos(rposSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k_sw(k_swSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type subdivisions(subdivisionsSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< double >::type abs_tol(abs_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(dwba_segment_integrals_cpp(rpos, k_sw, theta, h, R, subdivisions, rel_tol, abs_tol));
    return rcpp_result_gen;
END_RCPP
}
// gauss_legendre_cpp
List gauss_legendre_cpp(int n, double a, double b);
RcppExport SEXP _acousticTS_gauss_legendre_cpp(SEXP nSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(gauss_legendre_cpp(n, a, b));
    return rcpp_result_gen;
END_RCPP
}
// elastic_shell_boundary_conditions_old
ComplexMatrix elastic_shell_boundary_conditions_old(NumericVector k1a, NumericVector kLa_shell, NumericVector kTa_shell, NumericVector kLa_fluid, NumericVector kTa_fluid, NumericVector k3a_fluid, IntegerVector m_vec, double lambda, double mu, double rho_ratio_sw, double rho_ratio_fl);
RcppExport SEXP _acousticTS_elastic_shell_boundary_conditions_old(SEXP k1aSEXP, SEXP kLa_shellSEXP, SEXP kTa_shellSEXP, SEXP kLa_fluidSEXP, SEXP kTa_fluidSEXP, SEXP k3a_fluidSEXP, SEXP m_vecSEXP, SEXP lambdaSEXP, SEXP muSEXP, SEXP rho_ratio_swSEXP, SEXP rho_ratio_flSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type k1a(k1aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kLa_shell(kLa_shellSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kTa_shell(kTa_shellSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kLa_fluid(kLa_fluidSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type kTa_fluid(kTa_fluidSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k3a_fluid(k3a_fluidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type m_vec(m_vecSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type rho_ratio_sw(rho_ratio_swSEXP);
    Rcpp::traits::input_parameter< double >::type rho_ratio_fl(rho_ratio_flSEXP);
    rcpp_result_gen = Rcpp::wrap(elastic_shell_boundary_conditions_old(k1a, kLa_shell, kTa_shell, kLa_fluid, kTa_fluid, k3a_fluid, m_vec, lambda, mu, rho_ratio_sw, rho_ratio_fl));
    return rcpp_result_gen;
END_RCPP
}
// elastic_shell_boundary_conditions
ComplexMatrix elastic_shell_boundary_conditions(NumericMatrix ka_matrix, IntegerVector m_limit, double lambda, double mu, double rho_ratio_sw, double rho_ratio_fl);
RcppExport SEXP _acousticTS_elastic_shell_boundary_conditions(SEXP ka_matrixSEXP, SEXP m_limitSEXP, SEXP lambdaSEXP, SEXP muSEXP, SEXP rho_ratio_swSEXP, SEXP rho_ratio_flSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ka_matrix(ka_matrixSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type m_limit(m_limitSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type rho_ratio_sw(rho_ratio_swSEXP);
    Rcpp::traits::input_parameter< double >::type rho_ratio_fl(rho_ratio_flSEXP);
    rcpp_result_gen = Rcpp::wrap(elastic_shell_boundary_conditions(ka_matrix, m_limit, lambda, mu, rho_ratio_sw, rho_ratio_fl));
    return rcpp_result_gen;
END_RCPP
}
// Pn_cpp
NumericMatrix Pn_cpp(NumericVector n, NumericVector x);
RcppExport SEXP _acousticTS_Pn_cpp(SEXP nSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Pn_cpp(n, x));
    return rcpp_result_gen;
END_RCPP
}
// Pn_deriv_cpp
NumericMatrix Pn_deriv_cpp(NumericVector n, NumericVector x, int k);
RcppExport SEXP _acousticTS_Pn_deriv_cpp(SEXP nSEXP, SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(Pn_deriv_cpp(n, x, k));
    return rcpp_result_gen;
END_RCPP
}
// Qn_cpp
Rcpp::ComplexMatrix Qn_cpp(NumericVector nu, NumericVector x);
RcppExport SEXP _acousticTS_Qn_cpp(SEXP nuSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Qn_cpp(nu, x));
    return rcpp_result_gen;
END_RCPP
}
// Qn_deriv_cpp
ComplexMatrix Qn_deriv_cpp(NumericVector n, NumericVector x, int k);
RcppExport SEXP _acousticTS_Qn_deriv_cpp(SEXP nSEXP, SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(Qn_deriv_cpp(n, x, k));
    return rcpp_result_gen;
END_RCPP
}
// Smn_cpp
Rcpp::List Smn_cpp(Rcpp::IntegerVector m, Rcpp::IntegerVector n, double c, Rcpp::NumericVector arg, bool normalize, std::string precision);
RcppExport SEXP _acousticTS_Smn_cpp(SEXP mSEXP, SEXP nSEXP, SEXP cSEXP, SEXP argSEXP, SEXP normalizeSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type arg(argSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(Smn_cpp(m, n, c, arg, normalize, precision));
    return rcpp_result_gen;
END_RCPP
}
// Rmn_cpp
Rcpp::List Rmn_cpp(Rcpp::IntegerVector m, Rcpp::IntegerVector n, double c, double x1, int kind, std::string precision);
RcppExport SEXP _acousticTS_Rmn_cpp(SEXP mSEXP, SEXP nSEXP, SEXP cSEXP, SEXP x1SEXP, SEXP kindSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< int >::type kind(kindSEXP);
    Rcpp::traits::input_parameter< std::string >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(Rmn_cpp(m, n, c, x1, kind, precision));
    return rcpp_result_gen;
END_RCPP
}
// prolate_spheroid_fbs
Rcpp::ComplexVector prolate_spheroid_fbs(Rcpp::DataFrame acoustics, Rcpp::DataFrame body, Rcpp::DataFrame medium, Rcpp::List integration_pts, std::string precision, std::string Amn_method, bool adaptive);
RcppExport SEXP _acousticTS_prolate_spheroid_fbs(SEXP acousticsSEXP, SEXP bodySEXP, SEXP mediumSEXP, SEXP integration_ptsSEXP, SEXP precisionSEXP, SEXP Amn_methodSEXP, SEXP adaptiveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type acoustics(acousticsSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type body(bodySEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type medium(mediumSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type integration_pts(integration_ptsSEXP);
    Rcpp::traits::input_parameter< std::string >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< std::string >::type Amn_method(Amn_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type adaptive(adaptiveSEXP);
    rcpp_result_gen = Rcpp::wrap(prolate_spheroid_fbs(acoustics, body, medium, integration_pts, precision, Amn_method, adaptive));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_acousticTS_jc_cpp", (DL_FUNC) &_acousticTS_jc_cpp, 2},
    {"_acousticTS_yc_cpp", (DL_FUNC) &_acousticTS_yc_cpp, 2},
    {"_acousticTS_hc_cpp", (DL_FUNC) &_acousticTS_hc_cpp, 2},
    {"_acousticTS_jc_deriv_cpp", (DL_FUNC) &_acousticTS_jc_deriv_cpp, 3},
    {"_acousticTS_yc_deriv_cpp", (DL_FUNC) &_acousticTS_yc_deriv_cpp, 3},
    {"_acousticTS_hc_deriv_cpp", (DL_FUNC) &_acousticTS_hc_deriv_cpp, 3},
    {"_acousticTS_js_cpp", (DL_FUNC) &_acousticTS_js_cpp, 2},
    {"_acousticTS_ys_cpp", (DL_FUNC) &_acousticTS_ys_cpp, 2},
    {"_acousticTS_hs_cpp", (DL_FUNC) &_acousticTS_hs_cpp, 2},
    {"_acousticTS_js_deriv_cpp", (DL_FUNC) &_acousticTS_js_deriv_cpp, 3},
    {"_acousticTS_ys_deriv_cpp", (DL_FUNC) &_acousticTS_ys_deriv_cpp, 3},
    {"_acousticTS_hs_deriv_cpp", (DL_FUNC) &_acousticTS_hs_deriv_cpp, 3},
    {"_acousticTS_dwba_fbs_cpp", (DL_FUNC) &_acousticTS_dwba_fbs_cpp, 8},
    {"_acousticTS_dwba_segment_integrals_cpp", (DL_FUNC) &_acousticTS_dwba_segment_integrals_cpp, 8},
    {"_acousticTS_gauss_legendre_cpp", (DL_FUNC) &_acousticTS_gauss_legendre_cpp, 3},
    {"_acousticTS_elastic_shell_boundary_conditions_old", (DL_FUNC) &_acousticTS_elastic_shell_boundary_conditions_old, 11},
    {"_acousticTS_elastic_shell_boundary_conditions", (DL_FUNC) &_acousticTS_elastic_shell_boundary_conditions, 6},
    {"_acousticTS_Pn_cpp", (DL_FUNC) &_acousticTS_Pn_cpp, 2},
    {"_acousticTS_Pn_deriv_cpp", (DL_FUNC) &_acousticTS_Pn_deriv_cpp, 3},
    {"_acousticTS_Qn_cpp", (DL_FUNC) &_acousticTS_Qn_cpp, 2},
    {"_acousticTS_Qn_deriv_cpp", (DL_FUNC) &_acousticTS_Qn_deriv_cpp, 3},
    {"_acousticTS_Smn_cpp", (DL_FUNC) &_acousticTS_Smn_cpp, 6},
    {"_acousticTS_Rmn_cpp", (DL_FUNC) &_acousticTS_Rmn_cpp, 6},
    {"_acousticTS_prolate_spheroid_fbs", (DL_FUNC) &_acousticTS_prolate_spheroid_fbs, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_acousticTS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
