name: testthat-CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install dependencies
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      # Run tests
      - name: Run tests
        run: |
          Rscript -e 'library(testthat); test_dir("tests")'
        shell: Rscript {0}